FirstDjango/FirstDjango/urls.py
from django.contrib import admin
from django.conf.urls import url, include


urlpatterns = [
    url(r'admin/', admin.site.urls),
    url(r'^TestApp/', include('TestApp.urls')),
]

FirstDjango/TestApp/urls.py
from django.conf.urls import url
from . import views

app_name = 'TestApp'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<id>[0-9]+)/$', views.detail, name='detail'),
    url(r'^(?P<id>[0-9]+)/fav/$', views.fav, name='fav'),
]

FirstDjango/TestApp/models.py
# Create your models here.
from django.db import models

class AppDetails(models.Model):
    title = models.CharField(max_length=200)
    name = models.CharField(max_length=200)
    number = models.CharField(max_length=200)
    description = models.CharField(max_length=200)
    def __str__(self):
        return self.name + ' : ' + self.description

class Screen(models.Model):
    appdetails = models.ForeignKey(AppDetails, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    type = models.CharField(max_length=200)
    is_fav = models.BooleanField(default=False)
    def __str__(self):
        return self.title

FirstDjango/TestApp/views.py
from django.shortcuts import render
from django.http import  HttpResponse
from django.template import loader
from TestApp.models import AppDetails, Screen
from django.shortcuts import render, get_object_or_404
from django.http import Http404
# Create your views here.

def index(request):
    all_apps = AppDetails.objects.all()
    # template = loader.get_template('TestApp/index.html')
    context = {
        'all_apps' : all_apps
    }
    # return HttpResponse(template.render(context, request))
    return render(request, 'TestApp/index.html', context)


def detail(request, id):
    # try:
    #     app = AppDetails.objects.get(pk=id)
    # except AppDetails.DoesNotExist:
    #     raise Http404('app detail does not exist')
    app = get_object_or_404(AppDetails, pk=id)
    return render(request, 'TestApp/detail.html', {'app' : app})

def fav(request, id):
    app = get_object_or_404(AppDetails, pk=id)
    print(app)
    print('******')
    try:
        selected_screen = app.screen_set.get(pk=request.POST['screen'])
        print('selected screen : ', selected_screen)
    except (KeyError, Screen.DoesNotExist):
        return render(request, 'TestApp/detail.html', {
            'app': app,
            'error_message' :   'You did not select a valid screen.'
        })
    else:
        selected_screen.is_fav = True
        selected_screen.save()
        return render(request, 'TestApp/detail.html', {'app': app})

FirstDjango/TestApp/templates/TestApp/detail.html
<h1>{{app.title}}</h1>
<h3>{{app.name}}</h3>

{% if error_message %}
    <p>{{ error_message }}</p>
{% endif %}

<form action="{% url 'TestApp:fav' app.id %}" method="post">
    {% csrf_token %}
    {% for screen in app.screen_set.all %}
        <input type="radio" id="screen((forloop.counter}}" name="screen" value="{{screen.id}}">
        <label for="screen((forloop.counter}}">
            {{screen.title}}
            {% if screen.is_fav %}
                <img src="http://icons.iconarchive.com/icons/paomedia/small-n-flat/16/star-icon.png"/>
            {% endif %}
        </label><br>
    {% endfor%}
<input type="submit" value="Fav">
</form>
<!--<ul>-->
    <!--{% for screen in app.screen_set.all %}-->
        <!--<li>{{screen.title}} - {{screen.type}}</li>-->
    <!--{% endfor %}-->

<!--</ul>-->

FirstDjango/TestApp/templates/TestApp/index.html
<h1>All applications List</h1>
<ul>
    {% for app in all_apps %}
    <li><a href="{% url 'TestApp:detail' app.id %}">{{app.title}}</a></li>
    {% endfor %}
</ul>